### ISSUE TITLE
Support for features seems to be missing

### ISSUE THREAD

**Issue by AndreasOM** [mainmatter/cargo-autoinherit#10]
I just ran this on one of our projects, and it totally wrecked it.
It looks like `features` support is missing, or not working.

For Example:
`chrono = { version = "0.4.31", features = ["serde"] }`
got replaced with
`chrono = "0.4.31"`

and
```
tokio = { version = "1.35.1", features = ["full"] }
tokio = "1.35.1"
```

**Comment by LukeMathWalker** [comment]
Can you link a minimum reproduction for us to test against?
E.g. was the list of features you "lost" specified in `workspace.dependencies` or in a member's manifest?

**Comment by AndreasOM** [comment]
It was in the workspace itself, not in one of the members.

Sorry, but a bit busy right now, so can't create a repro,
but can rerun now and then.

**Comment by LukeMathWalker** [comment]
That's enough to debug, I think I know where the issue is.

**Comment by AndreasOM** [comment]
Seems to work for our project now.
