### ISSUE TITLE
Crashing on `[dev_dependencies]`

### ISSUE THREAD

**Issue by Boshen** [mainmatter/cargo-autoinherit#18]
https://github.com/mainmatter/cargo-autoinherit/blob/eb922d3ea3d4376fca33fd5ef4a9ffe580b7f20c/src/lib.rs#L135-L138

This panics on `[dev_dependencies]` but I was confused by the panic until looking at the source code.

**Comment by LukeMathWalker** [comment]
I forgot the snake case variant was still accepted.
We need to fix this, for build dependencies as well.
