### ISSUE TITLE
[dependencies.package] replacement leads to TOML parse error

### ISSUE THREAD

**Issue by timonbimon** [mainmatter/cargo-autoinherit#23]
Hi Luca 👋

very useful little tool, thanks for open-sourcing it! 🙏

Just tried running it on our codebase and there's two little things I noticed (will open a second issue for number 2).

this one was really easy to fix manually, so no biggie, but still wanted to point it out. :) 

<img width="741" alt="image" src="https://github.com/mainmatter/cargo-autoinherit/assets/14793026/77215404-b53c-419d-b290-edf3fdd31aa8">

<img width="956" alt="image" src="https://github.com/mainmatter/cargo-autoinherit/assets/14793026/c6b1a8fc-79d3-4200-98dc-e768fea06cad">

**Comment by LukeMathWalker** [comment]
This is indeed a bug, thanks for reporting it!

**Comment by hdoordt** [comment]
Fixed with #27
