### ISSUE TITLE
[Feature Request] Feature Unification Setting

### ISSUE THREAD

**Issue by AlJohri** [mainmatter/cargo-autoinherit#26]
Currently `cargo-autoinherit` will keep features in the workspace members as opposed to unifying them and bringing them all into the central virtual manifest.

As an option, it would be great to use [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) to specify the union of all features in the virtual manifest and each workspace member would then just have: `clap = { workspace = true }` or `clap = { workspace = true, optional = true }`.

**Comment by teor2345** [comment]
> it would be great to use [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) to specify the union of all features in the virtual manifest and each workspace member would then just have: `clap = { workspace = true }` or `clap = { workspace = true, optional = true }`.

This seems like it could cause unintentional activation of features in crates that didn't previously have those features. Did you mean the intersection of all features, rather than the union of all features?

**Comment by AlJohri** [comment]
Reading the [feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) docs, we rely on the "additive" assumption of features:

>A consequence of this is that features should be additive. That is, enabling a feature should not disable functionality, and it should usually be safe to enable any combination of features. A feature should not introduce a [SemVer-incompatible change](https://doc.rust-lang.org/cargo/reference/features.html#semver-compatibility).

In our cargo workspace, if we generate a binary where crate binary X needs feature A and crate binary Y needs feature B, then our final two binaries will use both features X and Y.

As I understand it, this helps save on compilation time because we can compile the crate with both features X and Y just once rather than compiling it twice with the different feature combinations.

>This seems like it could cause unintentional activation of features in crates that didn't previously have those features.

I would hope for this to be an opt-in setting that a user can intentionally enable.

**Comment by LukeMathWalker** [comment]
There are other mechanisms to achieve what you're looking for—e.g. `cargo-hakari`, which may be superseded soon by https://github.com/rust-lang/rfcs/pull/3692. It's out of scope for this project.
